# Site settings
title: "\["Marcus Baw", "Baw Labs", "Baw Medical"\].each { |web| web.pages << blog }"
email: marcusbaw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marcus Baw - locum General Hacktitioner, doctor, pro-am Rubyist, Health IT oddball and Open Source zealot. My blogs range from local politics to tech tips, Health IT to recipes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pacharanero.github.com" # the base hostname & protocol for your site
twitter_username: marcus_baw
github_username:  pacharanero

# Build settings
markdown: kramdown
permalink: title
