# Site settings
title: Marcus Baw
email: marcusbaw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marcus Baw - General Hacktitioner, locum GP, pro-am Rubyist, Health IT 'maverick' and Open Source zealot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pacharanero.github.io" # the base hostname & protocol for your site
twitter_username: marcus_baw
github_username:  pacharanero

# Build settings
markdown: kramdown
permalink: /:title.html
